--
-- PostgreSQL database dump
--

\restrict dIs9z1NoViKbF2SFLyYjnNtQDeF3cOhr9hWZVMpePe95s68axNZfRx0AOcdPpFT

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admins (
    id integer NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(100),
    password_hash text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.admins OWNER TO postgres;

--
-- Name: admins_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_schedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_schedule (
    id integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    period_label character varying(50),
    title character varying(255) NOT NULL,
    scope character varying(255),
    pic character varying(255),
    status character varying(20) DEFAULT 'scheduled'::character varying NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT audit_schedule_status_check CHECK (((status)::text = ANY ((ARRAY['scheduled'::character varying, 'ongoing'::character varying, 'completed'::character varying, 'cancelled'::character varying])::text[])))
);


ALTER TABLE public.audit_schedule OWNER TO postgres;

--
-- Name: audit_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_schedule ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.audit_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.documents (
    id integer NOT NULL,
    department_id integer NOT NULL,
    section_id integer,
    title character varying(255) NOT NULL,
    revision integer DEFAULT 1 NOT NULL,
    file_path text NOT NULL,
    uploaded_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.documents OWNER TO postgres;

--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: education_documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.education_documents (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    category character varying(100) NOT NULL,
    language character varying(20) DEFAULT 'Indonesia'::character varying NOT NULL,
    file_path text NOT NULL,
    uploaded_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.education_documents OWNER TO postgres;

--
-- Name: education_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.education_documents_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.education_documents_id_seq OWNER TO postgres;

--
-- Name: education_documents_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.education_documents_id_seq OWNED BY public.education_documents.id;


--
-- Name: form_cs_documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.form_cs_documents (
    id integer NOT NULL,
    category character varying(30) NOT NULL,
    control_no character varying(100) NOT NULL,
    title character varying(255) NOT NULL,
    language character varying(100) NOT NULL,
    file_path text NOT NULL,
    uploaded_at timestamp with time zone DEFAULT now() NOT NULL,
    keterangan_type character varying(30) DEFAULT 'none'::character varying NOT NULL,
    keterangan_note text,
    file_variant character varying(10),
    file_kind character varying(10) DEFAULT 'pdf'::character varying NOT NULL,
    title_emphasis_from integer,
    CONSTRAINT form_cs_documents_category_check CHECK (((category)::text = ANY (ARRAY[('form-aplikasi'::character varying)::text, ('kontrol-cs'::character varying)::text]))),
    CONSTRAINT form_cs_documents_file_kind_check CHECK (((file_kind)::text = ANY ((ARRAY['pdf'::character varying, 'xls'::character varying])::text[]))),
    CONSTRAINT form_cs_documents_keterangan_type_check CHECK (((keterangan_type)::text = ANY ((ARRAY['none'::character varying, 'plain-note'::character varying, 'web-base-approval'::character varying, 'list-all-daftar'::character varying])::text[])))
);


ALTER TABLE public.form_cs_documents OWNER TO postgres;

--
-- Name: form_cs_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.form_cs_documents ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.form_cs_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: form_cs_group_headers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.form_cs_group_headers (
    id integer NOT NULL,
    category character varying(30) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    label character varying(255) NOT NULL,
    control_no_prefix character varying(100),
    CONSTRAINT form_cs_group_headers_category_check CHECK (((category)::text = ANY ((ARRAY['form-aplikasi'::character varying, 'kontrol-cs'::character varying])::text[])))
);


ALTER TABLE public.form_cs_group_headers OWNER TO postgres;

--
-- Name: form_cs_group_headers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.form_cs_group_headers ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.form_cs_group_headers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hero_slides; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hero_slides (
    id integer NOT NULL,
    media_type character varying(10) NOT NULL,
    file_path text NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    cta_label character varying(100),
    cta_href character varying(255),
    sort_order integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT hero_slides_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['video'::character varying, 'image'::character varying])::text[])))
);


ALTER TABLE public.hero_slides OWNER TO postgres;

--
-- Name: hero_slides_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hero_slides ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.hero_slides_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: home_canvas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.home_canvas (
    id integer DEFAULT 1 NOT NULL,
    blocks jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_by integer,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT home_canvas_id_check CHECK ((id = 1))
);


ALTER TABLE public.home_canvas OWNER TO postgres;

--
-- Name: nav_labels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nav_labels (
    key character varying(50) NOT NULL,
    label character varying(100) NOT NULL
);


ALTER TABLE public.nav_labels OWNER TO postgres;

--
-- Name: photo_video_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.photo_video_requests (
    id integer NOT NULL,
    request_type character varying(20) NOT NULL,
    nik character varying(50),
    requester_name character varying(255) NOT NULL,
    dept_or_company character varying(255) NOT NULL,
    dept character varying(255),
    dept_pic_kamera character varying(255),
    from_at timestamp with time zone NOT NULL,
    to_at timestamp with time zone NOT NULL,
    location character varying(255) NOT NULL,
    objective text NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    submitted_at timestamp with time zone DEFAULT now() NOT NULL,
    decided_at timestamp with time zone,
    decided_by character varying(255),
    decision_note text,
    CONSTRAINT photo_video_requests_dates_check CHECK ((to_at >= from_at)),
    CONSTRAINT photo_video_requests_request_type_check CHECK (((request_type)::text = ANY ((ARRAY['internal'::character varying, 'visitor'::character varying])::text[]))),
    CONSTRAINT photo_video_requests_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[])))
);


ALTER TABLE public.photo_video_requests OWNER TO postgres;

--
-- Name: photo_video_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.photo_video_requests ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.photo_video_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: policy_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.policy_images (
    id integer NOT NULL,
    file_name character varying(255) NOT NULL,
    mime_type character varying(100) NOT NULL,
    file_path text NOT NULL,
    display_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.policy_images OWNER TO postgres;

--
-- Name: policy_images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.policy_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.policy_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: procedure_documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.procedure_documents (
    id integer NOT NULL,
    control_no character varying(100) NOT NULL,
    title character varying(255) NOT NULL,
    revision integer DEFAULT 1 NOT NULL,
    elf_date date NOT NULL,
    file_path text NOT NULL,
    uploaded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT procedure_documents_revision_check CHECK ((revision > 0))
);


ALTER TABLE public.procedure_documents OWNER TO postgres;

--
-- Name: procedure_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.procedure_documents ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.procedure_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sections; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sections (
    id integer NOT NULL,
    department_id integer NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.sections OWNER TO postgres;

--
-- Name: sections_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_schedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.training_schedule (
    id integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    period_label character varying(50),
    title character varying(255) NOT NULL,
    audience character varying(255),
    pic character varying(255),
    status character varying(20) DEFAULT 'scheduled'::character varying NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT training_schedule_status_check CHECK (((status)::text = ANY ((ARRAY['scheduled'::character varying, 'ongoing'::character varying, 'completed'::character varying, 'cancelled'::character varying])::text[])))
);


ALTER TABLE public.training_schedule OWNER TO postgres;

--
-- Name: training_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.training_schedule ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.training_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: working_standard_documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.working_standard_documents (
    id integer NOT NULL,
    control_no character varying(100) NOT NULL,
    title character varying(255) NOT NULL,
    revision integer DEFAULT 1 NOT NULL,
    file_path text NOT NULL,
    uploaded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT working_standard_documents_revision_check CHECK ((revision > 0))
);


ALTER TABLE public.working_standard_documents OWNER TO postgres;

--
-- Name: working_standard_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.working_standard_documents ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.working_standard_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: education_documents id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.education_documents ALTER COLUMN id SET DEFAULT nextval('public.education_documents_id_seq'::regclass);


--
-- Name: admins admins_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_email_key UNIQUE (email);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);


--
-- Name: admins admins_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_username_key UNIQUE (username);


--
-- Name: audit_schedule audit_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_schedule
    ADD CONSTRAINT audit_schedule_pkey PRIMARY KEY (id);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: departments departments_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_slug_key UNIQUE (slug);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: education_documents education_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.education_documents
    ADD CONSTRAINT education_documents_pkey PRIMARY KEY (id);


--
-- Name: form_cs_documents form_cs_documents_category_control_no_variant_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.form_cs_documents
    ADD CONSTRAINT form_cs_documents_category_control_no_variant_key UNIQUE (category, control_no, file_variant);


--
-- Name: form_cs_documents form_cs_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.form_cs_documents
    ADD CONSTRAINT form_cs_documents_pkey PRIMARY KEY (id);


--
-- Name: form_cs_group_headers form_cs_group_headers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.form_cs_group_headers
    ADD CONSTRAINT form_cs_group_headers_pkey PRIMARY KEY (id);


--
-- Name: hero_slides hero_slides_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hero_slides
    ADD CONSTRAINT hero_slides_pkey PRIMARY KEY (id);


--
-- Name: home_canvas home_canvas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.home_canvas
    ADD CONSTRAINT home_canvas_pkey PRIMARY KEY (id);


--
-- Name: nav_labels nav_labels_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nav_labels
    ADD CONSTRAINT nav_labels_pkey PRIMARY KEY (key);


--
-- Name: photo_video_requests photo_video_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photo_video_requests
    ADD CONSTRAINT photo_video_requests_pkey PRIMARY KEY (id);


--
-- Name: policy_images policy_images_file_path_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.policy_images
    ADD CONSTRAINT policy_images_file_path_key UNIQUE (file_path);


--
-- Name: policy_images policy_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.policy_images
    ADD CONSTRAINT policy_images_pkey PRIMARY KEY (id);


--
-- Name: procedure_documents procedure_documents_control_no_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.procedure_documents
    ADD CONSTRAINT procedure_documents_control_no_key UNIQUE (control_no);


--
-- Name: procedure_documents procedure_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.procedure_documents
    ADD CONSTRAINT procedure_documents_pkey PRIMARY KEY (id);


--
-- Name: sections sections_department_id_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_department_id_slug_key UNIQUE (department_id, slug);


--
-- Name: sections sections_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_pkey PRIMARY KEY (id);


--
-- Name: training_schedule training_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.training_schedule
    ADD CONSTRAINT training_schedule_pkey PRIMARY KEY (id);


--
-- Name: working_standard_documents working_standard_documents_control_no_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.working_standard_documents
    ADD CONSTRAINT working_standard_documents_control_no_key UNIQUE (control_no);


--
-- Name: working_standard_documents working_standard_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.working_standard_documents
    ADD CONSTRAINT working_standard_documents_pkey PRIMARY KEY (id);


--
-- Name: audit_schedule_date_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX audit_schedule_date_idx ON public.audit_schedule USING btree (start_date);


--
-- Name: form_cs_documents_category_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX form_cs_documents_category_idx ON public.form_cs_documents USING btree (category, control_no);


--
-- Name: form_cs_group_headers_category_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX form_cs_group_headers_category_idx ON public.form_cs_group_headers USING btree (category, sort_order);


--
-- Name: hero_slides_sort_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX hero_slides_sort_idx ON public.hero_slides USING btree (sort_order);


--
-- Name: photo_video_requests_status_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX photo_video_requests_status_idx ON public.photo_video_requests USING btree (status, submitted_at DESC);


--
-- Name: photo_video_requests_type_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX photo_video_requests_type_idx ON public.photo_video_requests USING btree (request_type, submitted_at DESC);


--
-- Name: policy_images_order_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX policy_images_order_idx ON public.policy_images USING btree (display_order, id);


--
-- Name: procedure_documents_control_no_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX procedure_documents_control_no_idx ON public.procedure_documents USING btree (control_no);


--
-- Name: training_schedule_date_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX training_schedule_date_idx ON public.training_schedule USING btree (start_date);


--
-- Name: working_standard_documents_control_no_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX working_standard_documents_control_no_idx ON public.working_standard_documents USING btree (control_no);


--
-- Name: documents documents_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE CASCADE;


--
-- Name: documents documents_section_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(id) ON DELETE CASCADE;


--
-- Name: home_canvas home_canvas_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.home_canvas
    ADD CONSTRAINT home_canvas_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.admins(id) ON DELETE SET NULL;


--
-- Name: sections sections_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict dIs9z1NoViKbF2SFLyYjnNtQDeF3cOhr9hWZVMpePe95s68axNZfRx0AOcdPpFT

