import { Bell, ChevronRight } from 'lucide-react'
import { news } from '@/lib/portal-data'

export default function NewsPage() {
  return <section className="portal-surface rounded-xl border border-border bg-card p-7 max-[680px]:p-4">
    <div className="mb-7 flex items-end justify-between gap-5 border-b border-border pb-6 max-[680px]:flex-col max-[680px]:items-start"><div><p className="portal-eyebrow mb-2">Newsroom / Security communications</p><h2 className="text-2xl font-bold tracking-tight text-primary">Informasi Baru</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">News, notices, and updates from the Information Security team.</p></div><button type="button" className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground hover:bg-primary/90"><Bell className="size-4" />Mark all read</button></div>
    <div className="flex flex-col gap-3">{news.map((item, index) => <article className="group grid grid-cols-[42px_1fr_16px] items-center gap-4 rounded-lg border border-border p-4 transition-colors hover:border-accent hover:bg-secondary/40 max-[680px]:grid-cols-[34px_1fr_14px] max-[680px]:gap-3 max-[680px]:p-3" key={item[0]}><div className="grid size-9 place-items-center rounded-md bg-secondary text-xs font-bold text-primary max-[680px]:size-8">0{index + 1}</div><div><span className="text-[10px] font-bold uppercase tracking-[0.14em] text-accent-foreground">{item[3]}</span><h3 className="mt-1.5 text-sm font-semibold text-foreground group-hover:text-accent-foreground">{item[0]}</h3><p className="mt-1.5 text-xs leading-5 text-muted-foreground">{item[1]}</p><time className="mt-2 block text-[10px] text-muted-foreground">{item[2]}</time></div><ChevronRight className="size-4 text-muted-foreground transition-transform group-hover:translate-x-0.5" /></article>)}</div>
  </section>
}
